version: 2

# defaults: &defaults
#   docker:
#     - image: circleci/node:10.13.0

jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/
          paths:
            - .
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run unit tests
          command: npm test
  deploy:
    filter:
      branches:
        only: master
    docker:
      - image: circleci/node:10.13.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
