version: 2

# defaults: &defaults
#   docker:
#     - image: circleci/node:10.13.0

jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - run: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy
