version: 2

# defaults: &defaults
#   docker:
#     - image: circleci/node:10.13.0

jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: npm test
  publish:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: npm publish
