version: 2

# defaults: &defaults
#   docker:
#     - image: circleci/node:10.13.0

jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: Echo tag number
          command: echo Publishing version $CIRCLE_TAG to NPM package
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/
          paths:
            - .
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run unit tests
          command: npm test
  deploy:
    filter:
      branches:
        only: master
    docker:
      - image: circleci/node:10.13.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run:
          name: Echo tag number
          command: echo Publishing version $CIRCLE_TAG to NPM package
      - run:
          name: Set github username
          command: git config user.email $CIRCLE_USERNAME
      - run:
          name: Set github name
          command: git config user.name $CIRCLE_USERNAME
      - run:
          name: Set version to that in git tag
          command: npm --no-git-tag-version version $CIRCLE_TAG
      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - test:
          filters:
            tags:
              only: /^v.*/
          requires:
            - build
      - confirm-npm-publish:
          filters:
            tags:
              only: /^v.*/
          type: approval
          requires:
            - test
      - deploy:
          filters:
            tags:
              only: /^v.*/
          requires:
            - confirm-npm-publish
